### ISSUE TITLE
Can't select address 0x40

### ISSUE THREAD

**Issue by Vedeneb** [bonnyr/wokwi-pca9685-custom-chip#2]
Hi,

first of all, thanks a lot for this custom chip. It works great, except I can't select address 0x40, which sadly is exactly the address my hardware design uses (which is permanently installed, so I can't easily change it).

Looking at the datasheet and your code I think I already found the problem:

In your function `addr_pins_to_addr` you calculate the address using a for looping starting at 0, ending at 5, so the first 6 bits of the address bytes are set. 
Based on the datasheet the first bit (MSB) is always 1, which is why the address in the simulator is always off by one bit and I can't select address 0x40.
![image](https://user-images.githubusercontent.com/39202639/233380863-3ba2b02e-0f0c-4166-84fe-ca4a4d03170d.png)
https://cdn-shop.adafruit.com/datasheets/PCA9685.pdf

I guess it's easy to fix however it would break any existing projects using the component since the address would change...

**Comment by bonnyr** [comment]
I believe 0x40 is not a valid address sine you only have 6 bits with the range of 0 - 63 (0x3F)

Or am I missing something?

**Comment by Vedeneb** [comment]
Yep, you are missing the screenshot from the datasheet in my initial post :) The slave address is actually 7 bit, but the first Bit is fixed to 1, so actually the address range is from 0b1000000 (0x40) to 0b1111111 (0x7F)

**Comment by bonnyr** [comment]
Not reall, I did not miss that :)

The address ranges is still 6 bits, but you're right that it starts at offset 64...
What I should have done is to ignore bit 7 when specifed in i2c since for most comms it must be set to `1`

Let me see whether changing the detection mechanism in the i2c code (which I believe is as simple as masking bit 7 off) works.
If I do that, then existing projects are not impacted and you get your actual address range :)

**Comment by bonnyr** [comment]
I believe v0.1.1 sorts your issue out
